import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: "100%",
    backgroundColor: '#fff',
  },
  logo: {
    width: 300,
    height: 120,
    alignSelf: 'center',
    marginBottom: 10,
    marginTop: -20,
  },
  authMethodsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 30,
    marginTop: 10,
    width: '100%',
  },
  authButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#f5f5f5',
    marginHorizontal: 4,
  },
  authButtonActive: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#0d9b1e',
  },
  authButtonText: {
    marginLeft: 4,
    color: 'black',
    fontSize: 12,
  },
  authButtonTextActive: {
    color: '#0d9b1e',
    fontWeight: '600',
  },
  keyboardView: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 100,
    paddingBottom: 100,
    width: "100%",
  },
  welcomeContainer: {
    alignSelf: 'center',
    alignItems: 'center',
    marginBottom: 10,
    width: '100%',
  },
  subtitle: {
    fontSize: 20,
    color: 'black',
    marginTop: 8,
    marginBottom: 8,
    fontWeight: '600',
  },
  gradientLine: {
    height: 2,
    width: '80%',
    alignSelf: 'center',
    marginTop: 8,
  },
  title: {
    fontSize: 32,
    fontWeight: "bold",
    marginBottom: 24,
    alignSelf: "flex-start",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 25,
    marginBottom: 20,
    paddingHorizontal: 20,
    height: 50,
    borderWidth: 1,
    borderColor: "#E1E0E0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  inputContainerError: {
    borderColor: '#ff0000',
    borderWidth: 2,
  },
  inputIcon: {
    marginRight: 12,
    color: '#16A34A',
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#333',
    paddingVertical: 0,
    height: '100%',
  },
  eyeIcon: {
    marginLeft: 8,
  },
  continueButton: {
    borderRadius: 25,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    marginVertical: 16,
    width: '100%',
  },
  continueButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
  },
  signupContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
    flexWrap: 'wrap',
  },
  signupText: {
    color: '#666',
    textAlign: 'center',
  },
  signupLink: {
    color: '#0d9b1e',
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  checkboxChecked: {
    backgroundColor: '#0d9b1e',
    borderColor: '#0d9b1e',
  },
  termsText: {
    fontSize: 14,
    color: '#666',
    flex: 1,
    flexWrap: 'wrap',
  },
  termsLink: {
    color: '#0d9b1e',
    textDecorationLine: 'underline',
  },
  forgotPasswordContainer: {
    alignSelf: 'flex-start',
    marginBottom: 1,
  },
  forgotPasswordText: {
    color: '#0d9b1e',
    fontSize: 14,
    fontWeight: '500',
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
    width: '100%',
    marginTop: 10,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#e0e0e0',
  },
  dividerText: {
    marginHorizontal: 10,
    color: '#666',
    fontSize: 14,
  },
  tabBarContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 60,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    zIndex: 1000,
  },
  socialButton: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 10,
    height: 50,
    marginTop: 16,
    paddingHorizontal: 16,
    justifyContent: "center",
  },
  googleButton: {
    borderWidth: 1,
    borderColor: "#4285F4",
    backgroundColor: "#fff",
  },
  googleButtonText: {
    fontSize: 16,
    color: "#4285F4",
    marginLeft: 12,
    fontWeight: "600",
  },
  facebookButton: {
    backgroundColor: "#1877F2",
  },
  facebookButtonText: {
    fontSize: 16,
    color: "#fff",
    marginLeft: 12,
    fontWeight: "600",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: '#fff',
    borderRadius: 15,
    width: '90%',
    maxHeight: '80%',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalContent: {
    padding: 20,
    maxHeight: '85%',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#0d9b1e',
    marginBottom: 15,
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginTop: 15,
    marginBottom: 8,
  },
  disclaimerText: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
    textAlign: 'justify',
    marginBottom: 10,
  },
  contactContainer: {
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  contactText: {
    fontSize: 13,
    color: '#666',
    marginBottom: 4,
    textAlign: 'center',
  },
  modalAcceptButton: {
    marginHorizontal: 20,
    marginVertical: 15,
  },
  modalButtonGradient: {
    borderRadius: 25,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  modalAcceptButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
  },
});