import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  termsContainer: {
    width: '100%',
    marginVertical: 8,
    paddingHorizontal: 16,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    width: '100%',
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#666',
    marginRight: 10,
    marginTop: 3,
    marginLeft: -10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#0d9b1e',
    borderColor: '#0d9b1e',
  },
  termsTextContainer: {
    flex: 1,
  },
  termsText: {
    color: '#666',
    fontSize: 14,
    lineHeight: 20,
  },
  termsLink: {
    color: '#0d9b1e',
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  loginContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
    flexWrap: 'wrap',
  },
  loginText: {
    color: '#666',
    textAlign: 'center',
  },
  loginLink: {
    color: '#0d9b1e',
    fontWeight: '600',
    textDecorationLine: 'underline',
  },

  container: {
    flex: 1,
    width: "100%",
    backgroundColor: '#fff',
  },
  keyboardView: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 80,
    paddingBottom: 100,
    width: "100%",
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 12,
    alignSelf: "center",
    textAlign: "center",
    width: '100%',
  },
  titleUnderline: {
    height: 6,
    width: '30%',
    alignSelf: 'center',
    marginTop: -8,
    marginBottom: 24,
    borderRadius: 3,
  },
  sectionContainer: {
    width: '100%',
    marginBottom: 16,
    backgroundColor: 'transparent',
    padding: 0,
  },
  sectionTitle: {
    fontSize: 18,
    color: '#16A34A',
    marginBottom: 16,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 25,
    marginBottom: 16,
    paddingHorizontal: 20,
    height: 50,
    borderWidth: 1,
    borderColor: "#E1E0E0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  inputContainerError: {
    borderColor: '#ff0000',
    borderWidth: 2,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#333',
    paddingVertical: 0,
    height: '100%',
    marginLeft: 0,
  },
  inputIcon: {
    marginRight: 12,
    color: '#16A34A',
  },
  buttonContainer: {
    width: '100%',
    paddingHorizontal: 16,
    marginTop: -10,
  },
  sectionToggleContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    backgroundColor: '#f0f0f0',
    borderRadius: 8,
    padding: 4,
    marginHorizontal: 16,
  },
  sectionToggle: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 6,
  },
  activeSectionToggle: {
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  sectionToggleText: {
    fontSize: 16,
    color: '#666',
    fontWeight: '500',
  },
  activeSectionToggleText: {
    color: '#16A34A',
    fontWeight: '600',
  },
  titleInput: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 8,
  },
  selectedText: {
    fontSize: 16,
    color: '#000',
  },
  dropdownIcon: {
    marginLeft: 8,
  },
  dropdownContainer: {
    marginTop: -8,
    marginBottom: 8,
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E1E0E0',
    maxHeight: 200,
    zIndex: 1000,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  dropdownItem: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    minHeight: 20,
    justifyContent: 'center',
  },
  dropdownItemText: {
    fontSize: 16,
    color: '#333',
  },
  genderInput: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 8,
  },
  genderSelected: {
    backgroundColor: '#e6f7e6',
    borderColor: '#0d9b1e',
  },
  genderText: {
    color: '#666',
    fontSize: 14,
  },
  genderTextSelected: {
    color: '#0d9b1e',
    fontWeight: '600',
  },
  dateInput: {
    flex: 1,
    justifyContent: 'center',
    height: '100%',
  },
  dateText: {
    fontSize: 16,
    color: '#000',
  },
  placeholderText: {
    fontSize: 16,
    color: '#999',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '80%',
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 20,
    textAlign: 'center',
  },
  dateFormatLabel: {
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
    fontWeight: '600',
  },
  dateFormatExample: {
    fontSize: 13,
    color: '#999',
    marginBottom: 16,
    fontStyle: 'italic',
  },
  dateInputContainer: {
    position: 'relative',
    marginBottom: 20,
  },
  dateInputField: {
    borderWidth: 1,
    borderColor: '#E1E0E0',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    letterSpacing: 1,
  },
  floatingPlaceholder: {
    position: 'absolute',
    top: 14,
    left: 12,
    fontSize: 16,
    color: '#ccc',
    pointerEvents: 'none',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginHorizontal: 5,
  },
  cancelButton: {
    backgroundColor: '#f5f5f5',
  },
  saveButton: {
    backgroundColor: '#16A34A',
  },
  cancelButtonText: {
    color: '#666',
    fontWeight: '600',
  },
  saveButtonText: {
    color: 'white',
    fontWeight: '600',
  },
  eyeIcon: {
    marginLeft: 8,
  },
  continueButton: {
    borderRadius: 25,
    paddingVertical: 15,
    alignItems: 'center',
    marginBottom: 20,
    width: '100%',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  continueButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
  },
  footerText: {
    textAlign: "center",
    fontSize: 14,
    color: "#333",
  },
  resetLink: {
    color: "#000",
    fontWeight: "600",
    marginLeft: 4,
  },
  tabBarContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 60,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    zIndex: 1000,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  disclaimerModalContainer: {
    backgroundColor: '#fff',
    borderRadius: 15,
    width: '90%',
    maxHeight: '80%',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  disclaimerModalContent: {
    padding: 20,
    maxHeight: '85%',
  },
  disclaimerModalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#0d9b1e',
    marginBottom: 15,
    textAlign: 'center',
  },
  disclaimerSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginTop: 15,
    marginBottom: 8,
  },
  disclaimerText: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
    textAlign: 'justify',
    marginBottom: 10,
  },
  disclaimerContactContainer: {
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  disclaimerContactText: {
    fontSize: 13,
    color: '#666',
    marginBottom: 4,
    textAlign: 'center',
  },
  disclaimerAcceptButton: {
    marginHorizontal: 20,
    marginVertical: 15,
  },
  disclaimerButtonGradient: {
    borderRadius: 25,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  disclaimerAcceptButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
  },
});