import { StyleSheet, Platform, StatusBar } from "react-native";

export const styles = StyleSheet.create({
  safeWrap: {
    backgroundColor: "#e6f4ea",
  },
  container: {
    backgroundColor: "#fff",
  },
  wrap: {
    backgroundColor: "#e6f4ea",
    paddingTop: Platform.OS === "android" ? Math.max((StatusBar.currentHeight || 0) - 12, 0) : 0,
    paddingBottom: 12,
    paddingHorizontal: 16,
  },
  topRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  title: {
    fontSize: 18,
    fontWeight: "700",
    color: "#333",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  searchBar: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    borderRadius: 25,
    paddingHorizontal: 12,
    height: 45,
    marginRight: 10,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: "#333",
    paddingVertical: 8,
  },
  clearButton: {
    padding: 4,
  },
  filterButton: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: "#e8f5e9",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#0d9b1e",
  },
  cityBtn: {
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "#cfe9db",
    backgroundColor: "#fff",
    paddingHorizontal: 50,
    paddingVertical: 8,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
  },
  cityText: {
    marginRight: 6,
    color: "#333",
    fontWeight: "600",
  },
  categoriesContainer: {
    backgroundColor: "#fff",
    paddingVertical: 10,
    maxHeight: 50,
  },
  categoriesContent: {
    paddingHorizontal: 16,
    alignItems: "center",
  },
  categoryChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#f5f5f5",
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  categoryChipActive: {
    backgroundColor: "#e8f5e9",
    borderColor: "#0d9b1e",
  },
  categoryText: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  categoryTextActive: {
    color: "#0d9b1e",
    fontWeight: "600",
  },
  tabsRow: {
    marginTop: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  tab: {
    flex: 1,
    alignItems: "center",
  },
  tabIcon: {
    width: 54,
    height: 54,
    borderRadius: 27,
    borderWidth: 2,
    borderColor: "#cfe9db",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#e6f4ea",
  },
  tabIconActive: {
    backgroundColor: "#0d9b1e",
    borderColor: "#0d9b1e",
  },
  tabLabel: {
    marginTop: 6,
    color: "#777",
    fontSize: 12,
    fontWeight: "600",
  },
  tabLabelActive: {
    color: "#0d9b1e",
    fontWeight: "700",
  },
  searchWrap: {
    marginTop: 16,
    height: 44,
    backgroundColor: "#fff",
    borderRadius: 22,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
});